server:
    mode: debug # debug or release
    port: 18080
    read_timeout: 60s
    write_timeout: 60s
database:
    type: mysql
    host: 127.0.0.1
    name: platform
    user: root
    password: test
cdn:
    all: https://cdn.domain.com
hash:
    salt: 
    alphabet: ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz123456789
mail:
    smtp: smtp.qq.com
    port: 587
    name: 
    address: 
    password: 
referer:
    domain:
        - domain.com
auth:
    secret: 
    expiration: 24