server:
    mode: debug # debug or release
    port: 8090
    read_timeout: 60s
    write_timeout: 60s
frontend:
    path: 
database:
    type: mysql
    host: 127.0.0.1
    name: example
    user: root
    password: example
hash:
    salt: 
    alphabet: ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz123456789